/*
 * The ONLY deployable module — assembles every bounded context into the
 * runnable Spring Boot application (JVM, not native — PLAN.md deviation
 * from HospitOps).
 *
 * @author Salman
 * @version 1.0
 * @since 2026-07-03
 */

plugins {
    id("org.springframework.boot")
}

dependencies {
    // ── Bounded-context modules ─────────────────────────────────────────
    implementation(project(":shared"))
    implementation(project(":account"))
    implementation(project(":property"))
    implementation(project(":ari"))
    implementation(project(":booking"))
    implementation(project(":channel"))

    // ── Infrastructure (as generated by start.spring.io for Boot 4.1.0) ─
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("org.springframework.boot:spring-boot-starter-flyway")
    implementation("org.springframework.boot:spring-boot-starter-jdbc")
    implementation("org.springframework.boot:spring-boot-starter-security")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation("org.springframework.boot:spring-boot-starter-webmvc")
    implementation("org.flywaydb:flyway-database-postgresql")

    developmentOnly("org.springframework.boot:spring-boot-docker-compose")
    runtimeOnly("org.postgresql:postgresql")

    // ── Test ────────────────────────────────────────────────────────────
    testImplementation("org.springframework.boot:spring-boot-starter-actuator-test")
    testImplementation("org.springframework.boot:spring-boot-starter-data-jpa-test")
    testImplementation("org.springframework.boot:spring-boot-starter-flyway-test")
    testImplementation("org.springframework.boot:spring-boot-starter-jdbc-test")
    testImplementation("org.springframework.boot:spring-boot-starter-security-test")
    testImplementation("org.springframework.boot:spring-boot-starter-validation-test")
    testImplementation("org.springframework.boot:spring-boot-starter-webmvc-test")
    testImplementation("org.springframework.boot:spring-boot-testcontainers")
    testImplementation("org.testcontainers:testcontainers-junit-jupiter")
    testImplementation("org.testcontainers:testcontainers-postgresql")
}

springBoot {
    mainClass.set("id.co.hospitomni.HospitomniApplication")
}
